In [1]:
import pandas as pd
import numpy as np

In [2]:
# Create a numpy array
a = np.array([2,3,8,4,5,6])
print(a)

[2 3 8 4 5 6]


In [3]:
arr = np.arange(1, 11, 2)
print(arr)

[1 3 5 7 9]


In [4]:
zero = np.zeros((3,3))
print(zero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
one = np.ones((3,3))
one

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
const_arr = np.full((2, 2), 8)
const_arr

array([[8, 8],
       [8, 8]])

In [7]:
iden = np.eye(5)
iden

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [8]:
ra = np.random.random((2, 4))
ra

array([[0.58940478, 0.98944537, 0.42832604, 0.6839942 ],
       [0.6185364 , 0.63065839, 0.69341327, 0.01434439]])

In [9]:
np.shape(ra)

(2, 4)

In [10]:
mat = np.array([[1, 2], [3, 4], [5, 6]])
print(mat)

[[1 2]
 [3 4]
 [5 6]]


In [11]:
print(mat[1,1])

4


In [12]:
dt_arr = np.arange(1, 11, dtype=np.float32)
print(dt_arr)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [13]:
c = complex(42, 1)
print(c)

(42+1j)


In [14]:
print(c.real, c.imag)

42.0 1.0


In [15]:
# manipulating array shaepes
arr = np.arange(1, 16)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [16]:
new_arr = arr.reshape(3, 5)
print(new_arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [17]:
a = [34, 43, 35, 45]

In [20]:
new_arr = np.concatenate((new_arr, a), axis=1)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [ ]:
arr2 = new_arr.flatten()
print(arr2)

In [ ]:
tra = new_arr.transpose()
print(tra)

In [ ]:
(arr.resize(1, 15))
print(arr)

In [ ]:
# horizontal stacking
arr1 = np.arange(1, 10).reshape(3, 3)
print(arr1)

In [ ]:
arr2 = arr1*2
print(arr2)

In [ ]:
arr3 = np.hstack((arr1, arr2))
print(arr3)

In [ ]:
arr4 = np.concatenate((arr1, arr2), axis=1)
print(arr4)

In [ ]:
arr5 = np.concatenate((arr1, arr2), axis=0)
print(arr5)

In [ ]:
# Partitioning arrays
arr = np.arange(1, 11).reshape(2, 5)
print(arr)

In [ ]:
arr_hor_split = np.hsplit(arr, 5)
print(arr_hor_split)

In [ ]:
arr_ver_split = np.vsplit(arr, 2)
print(arr_ver_split)

In [ ]:
# Changing dtypes of np array
arr = np.arange(1, 10).reshape(3, 3)
print(arr)

In [ ]:
arr = arr.astype(float)
print(arr)

In [ ]:
# Converting np arr to Python list
arr = np.arange(1, 10)
arr

In [ ]:
list1 = arr.tolist()
print(list1)

In [ ]:
# Numpy views and copies
arr = np.arange(1, 26).reshape(5, 5)
print(arr)

In [ ]:
# Deep Copy
arr_copy = arr.copy()
print(arr_copy)

In [ ]:
arr_view = arr.view()
print(arr_view)

In [ ]:
arr[1] = [-1, -2, -3, -4, -5]

In [ ]:
print(arr_copy)

In [ ]:
print(arr_view)

In [ ]:
arr_flat = arr.flatten()

In [ ]:
arr_flat[arr_flat>10]

In [ ]:
arr[arr>10]

In [ ]:
arr[[1,2]]

In [ ]:
# Pandas DataFrame

In [ ]:
df = pd.DataFrame()
df.head()

In [ ]:
data = {'Name': ['Unknown', 'Money', 'Career', 'Love'],
           'Age': [0, 2, 1000000000, 0]}
df = pd.DataFrame(data)
df

In [ ]:
dic1 = {'Ajay':1, 'Vijay':2, 'Dhananjay':3}
series = pd.Series(dic1)
series